### ISSUE TITLE
Move node-sass into peerDependencies

### ISSUE THREAD

**Issue by MarioSimou** [trofima/rollup-plugin-ejs#19]
Is it possible to move `node-sass` into `peerDependencies` in order to give us more flexibility upgrading the version node.js runtime? node-sass prevents us for upgrading to v18.x

**Comment by trofima** [comment]
Hi. try version 3.0.0 please

**Comment by trofima** [comment]
Alternatively you can use version 4.0.0
If you don't use `inlineStyles` option (former `loadStyles`), this plugin doesn't need `node-sass` dependency at all. In v4 I dynamically import `node-sass` only when it's really needed. So missing peer dependency warning for the plugin can be safely ignored in such case.

**Comment by MarioSimou** [comment]
Okay, thanks for that. I tested v3.x an hour ago and worked fine. I will also test v4.x in a moment
