### ISSUE TITLE
How to use it in typescript？

### ISSUE THREAD

**Issue by B1anker** [trofima/rollup-plugin-ejs#2]
My typescript doesn't allow me to import '*.ejs' like this.
![image](https://user-images.githubusercontent.com/17514962/32085812-eb52ec86-ba96-11e7-912a-c7f949c823e0.png)
Is there any way to resolve it?

**Comment by B1anker** [comment]
I create a declaration.d.ts in my project, there is another problem.
![image](https://user-images.githubusercontent.com/17514962/32779664-3ef9099e-c904-11e7-8599-d5f17e21a6ef.png)

**Comment by trofima** [comment]
Hi. Please show the contents of the src/tpl/test.ejs file.

As for declarations unfortunately I can't help you a lot, because I'm not so good in typescript. You can pull request your typings if you like and help all typescript users this way.

**Comment by haixuxu** [comment]
here is a solution!
1. use js to define a module
```js
import button from './widgets/button.tpl';


function tplfn(str) {
  console.log(button);
  return 'xxx';
}
export {tplfn};
export default function test() {
  console.log(button);

  return 'xxx';
}
```

2. declare a .d.ts file
```ts
type TplFunc = (str: string) => string;

declare let tplfn: TplFunc;

export {tplfn};
export default tplfn;
```

3. use plugin
```js
   ejs({
      include: ['src/tpl/**/*.tpl'], // optional, '**/*.ejs' by default
      compilerOptions: {client: true, _with: false}, // optional, any options supported by ejs compiler
    }),
```

_with flag is import for resolve a parse_error or strict mode error!
```sh
Error: 'with' in strict mode (Note that you need plugins to import files that are not JavaScript)
```
