### ISSUE TITLE
error: include is not a function 

### ISSUE THREAD

**Issue by S-ophie** [trofima/rollup-plugin-ejs#21]
when tpl.ejs only contains 

```
<p><%= locals.text %></p>
```

it works fine;

but

when it like this

```
<p><%= locals.options.container %></p>
<%- include ("./pause.ejs") %>
```

I got the error `include is not a function`

**Comment by trofima** [comment]
`include` is server side feature in EJS. The plugin is created for client side rendering. If you need to reuse some markup, extract it to a component. Actually this is common and recommended way for the client side.
